Implemented new changes
rabbitmq/rabbitmq-web-mqtt pull request #63
Opened 2019-12-24 09:17 UTC by Shambhavikumari

oAuth-token-based-Authentication before subscribing to a message already available in the broker.

2019-12-24 09:17 UTC, pivotal-issuemaster commented
@Shambhavikumari Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-web-mqtt&pullRequestId=63)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/rabbitmq-web-mqtt&pullRequestId=63) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2019-12-24 10:13 UTC, michaelklishin requested changes
Thanks.

Are you sure this PR was meant to be sent to this repository and not a custom fork of yours or something like that?

It would be nice to have some justification for the changes, including a problem statement, answers to a few questions in this review and a set of steps for us to reproduce the problem and see the effects of this change.

2019-12-24 10:13 UTC, michaelklishin commented on src/rabbit_web_mqtt_connection_sup.erl
> +%% at http://www.mozilla.org/MPL/
Please undo all changes not related to the problem at hand.

2019-12-24 10:13 UTC, michaelklishin commented on src/rabbit_web_mqtt_handler.erl
> +    ProcessorState = rabbit_mqtt_processor_custom:initial_state(Sock,
I don't think this module exists in the MQTT plugin.

2019-12-24 10:13 UTC, michaelklishin commented on src/rabbit_web_mqtt_handler.erl
> +        rabbit_mqtt_reader: ssl_login_custom_subscriber(),
I don't think this function exists in the MQTT plugin?

2019-12-24 10:13 UTC, michaelklishin commented on src/rabbit_web_mqtt_app.erl
> +  case ranch:start_listener(web_mqtt, get_env(num_tcp_acceptors, 10),
What's the reasoning behind moving away from map-based transport options here?

2019-12-24 10:32 UTC, michaelklishin commented
[rabbitmq-users thread](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/rabbitmq-users/uF05pvy8hk8/WhMCYZHlAAAJ) with some background.

2019-12-24 10:33 UTC, michaelklishin commented on src/rabbit_web_mqtt_handler.erl
> +    ProcessorState = rabbit_mqtt_processor_custom:initial_state(Sock,
Also, the name is not very specific. How exactly is "custom" different from a regular processor module? When should it be used? Why? The name raises a bunch of questions and answers none.

2019-12-27 04:34 UTC, michaelklishin commented
Instead of adding reverts or manual reverts to this PR create a new branch with only the relevant changes, and submit that with any dependencies necessary (this PR references modules that do not exist anywhere) some additional information requested above:

 * How do other RabbitMQ users benefit from this change?
 * How does it fit into the existing authN/authZ framework?
 * How do we test it?

2019-12-27 04:34 UTC, closed without merging